Домашняя работа разметка
htmlacademy-htmlcss/2297847-sedona-36 pull request #2
Opened 2023-01-25 06:53 UTC by spilo777

2023-01-27 09:07 UTC, mkolotovich requested changes
по заданию необходимо выполнить разметку страниц в файлах index.html и catalog.html (создать этот файл при необходимости), а вы разметили только файл index.html

2023-01-27 09:07 UTC, mkolotovich commented on index.html
> +        <!-- HEADER-END -->
пропустили закрывающий тег для HEADER

2023-01-27 09:07 UTC, mkolotovich commented on index.html
> +              <a class="navigation-link" href="about.html">Главная</a>
главная страница - это файл index.html, а не about.html

2023-01-27 09:07 UTC, mkolotovich commented on index.html
> +              <a class="navigation-link" href="№">О Седоне</a>
по заданию Если страницы нет в макете, то ссылка на неё должна быть следующего вида — `<a href="#"></a>`.

2023-01-27 09:07 UTC, mkolotovich commented on index.html
> +              <a class="navigation-link" href="about.html">Гостиницы</a>
здесь должна быть ссылка на страницу catalog.html

2023-01-27 09:07 UTC, mkolotovich commented on index.html
> +              </span>
зачем этот скрытый спан? уберите его он лишний

2023-01-27 09:07 UTC, mkolotovich commented on index.html
> +            </li>
вот это всё я бы обернул в отдельный список

2023-01-27 09:07 UTC, mkolotovich commented on index.html
> +          <img class="promo-welcome" src="" alt="Добро пожаловать!">
добавьте еще одно изображение с декоративной рамкой

2023-01-27 09:07 UTC, mkolotovich commented on index.html
> +            <h1 class="causes-hidden">Преимущества</h1>
такого текста нет в макете. Если вы хотите скрытый текст то на него по заданию необходимо вешать класс visually-hidden

2023-01-27 09:07 UTC, mkolotovich commented on index.html
> +              Седона круче, чем Гранд-Каньон!</h3>
это бы я разметил просто параграфом

2023-01-27 09:07 UTC, mkolotovich commented on index.html
> +              течёт своя жизнь</h3>
это я тоже предлагаю разметить параграфом

2023-01-27 09:07 UTC, mkolotovich commented on index.html
> +              течёт своя жизнь</h3>
вот это я бы обернул еще в один тег для удобства построения сетки, но можно это и потом сделать как дойдем до сеток

2023-01-27 09:07 UTC, mkolotovich commented on index.html
> +                </h3>
это я тоже предлагаю разметить параграфом

2023-01-27 09:07 UTC, mkolotovich commented on index.html
> +            <ul class="description-list">
не вижу смысла делать список из одного элемента. Я предлагаю сделать список из 3 элементов

2023-01-27 09:07 UTC, mkolotovich commented on index.html
> +            </ul>
предагаю эти карточки разметить по аналогии первой карточки

2023-01-27 09:07 UTC, mkolotovich commented on index.html
> +            </ul>
тут тоже сделайте как я писал выше

2023-01-27 09:07 UTC, mkolotovich commented on index.html
> +            <ul class="souvenirs-list">
опять списки из одного элемента. Лучше сделать список из 3 элементов.

2023-01-27 09:07 UTC, mkolotovich commented on index.html
> +              </span>
зачем тут скрытый спан? уберите его он лишний

2023-01-27 09:07 UTC, mkolotovich commented on index.html
> +          <div class="mailing">
если в блоке есть заголовок то его лучше обернуть в section, если заголовка в блоке нет то лучше использовать div.

2023-01-27 09:07 UTC, mkolotovich commented on index.html
> +          <ul class="icons-footer">
и снова списки из одного элемента. Лучше здесь тоже сделать список из 3 элементов

2023-01-27 09:15 UTC, spilo777 commented
Хорошо, все исправлю!)

2023-01-28 20:36 UTC, mkolotovich commented on index.html
> +            </ul>
куда дели карточку Красивая дорога? Верните её обратно)

2023-01-28 20:39 UTC, mkolotovich requested changes
исправьте не схлопнутые комментарии с прошлой проверки

2023-01-29 16:28 UTC, spilo777 commented
аккк

2023-01-31 19:48 UTC, mkolotovich requested changes

2023-01-31 19:48 UTC, mkolotovich commented on catalog.html
> +            <a class="breadcrumbs-link">Гостиницы</a>
по заданию - Если страницы нет в макете, то ссылка на неё должна быть следующего вида — `<a href="#"></a>`.

2023-01-31 19:48 UTC, mkolotovich commented on catalog.html
> +            <input class="hotel-price" type="text" name="hotel-price-till" id="hotel-price-till" value="9000">
вместо value я предлагаю использовать атрибут placeholder.Тогда пользователю не придется стирать предыдущее значение.

2023-01-31 19:48 UTC, mkolotovich commented on catalog.html
> +              <option value="cheap">Сначала дешёвые</option>
в макете - Сначала дешевые

2023-01-31 19:48 UTC, mkolotovich commented on catalog.html
> +                <a class="pagination-link pagination-disabled" href="#">
здесь я имел ввиду убрать класс visually-hidden у ссылок, а не контент. Контент верните)

2023-01-31 19:48 UTC, mkolotovich commented on catalog.html
> +              <input type="text" name="subscribe-news" placeholder="Ваш
уберите перенос строки и добавьте просто пробел между словами

2023-01-31 19:48 UTC, mkolotovich commented on catalog.html
> +                alt="Иконка ютуба">
здесь и на главной это всё таки должны быть ссылки, а не просто изображения соц.сетей

2023-02-01 20:09 UTC, merged